services:
  ollama:
    build:
      context: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  postgres:
    image: 'pgvector/pgvector:pg16'
    container_name: postgresx
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

#  pierrot-bot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: pierrot-bot
#    depends_on:
#      - ollama
#      - postgres
#    environment:
#    restart: unless-stopped

volumes:
  ollama_data:
  postgres_data: