spring:
  application:
    name: rolePlayBot

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  ai:
    ollama:
      base-url: http://ollama:11434

      chat:
        options:
          model: character
          temperature: 0.7
          num_ctx: 4096
          repeat_penalty: 1.1

      embedding:
        options:
          model: nomic-embed-text

  jpa:
    hibernate:
      ddl-auto: create
  flyway:
    enabled: true
    baseline-on-migrate: true

bot:
  token: ${DISCORD_TOKEN}
  client-username: ${DISCORD_USERNAME}
  owner-username: ${DISCORD_OWNER}
